approved = [
    "mit",
    "apache-2.0",
    "bsd-3-clause",
    "bsd-2-clause",
    "mpl-2.0",
]


ignored = [
    "emperror.dev/errors",
    "github.com/ghodss/yaml",
    "go.uber.org/atomic",
    "go.uber.org/multierr",
    "github.com/russross/blackfriday",
]
